# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MapsDirectionsGooglePlacesLBTA' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MapsDirectionsGooglePlacesLBTA
  pod 'GooglePlaces'
  pod 'GoogleMaps'

end
