# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwipeMatchFirestoreLBTA' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwipeMatchFirestoreLBTA
  pod 'Firebase/Firestore'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Core'
  pod 'SDWebImage','~>4.4.2'
  pod 'JGProgressHUD','~>2.0.3'
  pod 'LBTATools'

end
